### ISSUE TITLE
Build Script does not work for GNU Radio 3.10

### ISSUE THREAD

**Issue by GentlemanSch** [ThomasHabets/gr-habets39#2]
![image](https://github.com/ThomasHabets/gr-habets39/assets/25441680/e01cbfc9-536f-4016-a747-0847959ed95f)
![image](https://github.com/ThomasHabets/gr-habets39/assets/25441680/06221a2b-8f57-40c9-8b27-ec4f9c7018de)

The helper build file does not assist in building for some instances of GNU radio and causes confusion. I think it should be corrected or removed.

**Comment by ThomasHabets** [comment]
I am in the chat, but on the IRC side. And there seems to be a disconnection between IRC and… uh… Matrix? Discord? Wherever this screenshot is from.

Ah, Matrix.

Yeah, when I wrote `build.sh` I wasn't prepared for other people to use my code. :-)

I'll fix that. Thanks.
